from abc import ABC, abstractmethod

class BrokerAdapter(ABC):
    @abstractmethod
    async def account(self): ...
    @abstractmethod
    async def positions(self): ...
    @abstractmethod
    async def market_order(self, symbol, side, quantity): ...
    @abstractmethod
    async def cancel_order(self, order_id): ...
